# 인코딩(Encoding) & 디코딩(Decoding)

In [4]:
from sklearn.preprocessing import LabelEncoder

# List 생성
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']


# Create LabelEncoder model
encoder = LabelEncoder()


# fit & transform으로 레이블 인코딩 수행
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환 값 : ', labels)
print('인코딩 클래스 : ', encoder.classes_)

인코딩 변환 값 :  [0 1 4 5 3 3 2 2]
인코딩 클래스 :  ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [5]:
# 디코딩
decoder = encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3])
print('디코딩 원본 값 : ', decoder)

디코딩 원본 값 :  ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


# 
# 
# 

# 원-핫 인코딩(One-Hot Encoding)

In [16]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd


# Lable Encoder 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)


# 2차원 데이터로 변환
labels = labels.reshape(-1, 1)


# One-Hot Encoding 적용
OH_Encoder = OneHotEncoder()
OH_Encoder.fit(labels)
OH_Labels = OH_Encoder.transform(labels)
print('One-Hot Encoding Data')
print(OH_Labels.toarray())
print('One-Hot Encoding Data Dimension : ', OH_Labels.shape)


# Pandas.get_dummies를 이용하여 One-Hot Encoding 바로 적용 가능.
df = pd.DataFrame({'item':items})
pd.get_dummies(df)

One-Hot Encoding Data
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
One-Hot Encoding Data Dimension :  (8, 6)


item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

# 
# 
# 

# 피처 스케일링(Feature Scaling) 및 정규화(Normalization)

## 표준화(Standardization)
Data Feature의 각각 평균이 0 분산이 1인 가우시안 정규 분포를 가진 값으로 변환하는 것.

## 정규화(Normalization)
서로 다른 Feature의 크기를 통일하기 위해 크기를 변환해주는 개념.
### 

##### 사이킷런에서 제공하는 모듈과 일반적인 정규화에 약간 차이가 있다. 
##### 때문에 혼선을 방지하기 위해 일반적인 의미의 표준화와 정규화를 통들어 '피쳐 스케일링(Feature Scailng)으로 통칭한다.
##### 앞으로 선형대수 개념의 정규화를 벡터 정규화로 지칭한다. 
##### 클래스는 크게 StandardScaler와 MinMaxScaler로 나뉜다.

# StandardScaler

#### 표준화를 쉽게 지원하기 위한 클래스.
#### 개별 Feature를 평균이 0 이고 분산이 1 인 값(가우시안 정규 분포)으로 변환.
#### SVM(Support Vector Machine), Linear Regression, Logistic Regression 에서 해당 정규화(가우시안 분포) 데이터 사용

In [17]:
from sklearn.datasets import load_iris

# Data Load
iris = load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
print('Feature 들의 평균 값')
print(iris_df.mean())
print('\nFeature 들의 분산 값')
print(iris_df.var())

Feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

Feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [22]:
from sklearn.preprocessing import StandardScaler
# 각 Feature를 한 번에 표준화 변환.
# fit & transform 메서드 사용.
# transform() 의 결과 ndarray로 반환되므로 DataFrame 변환해서 사용할 것.


# StandardScaler 객체 생성
scaler = StandardScaler()


# Data Set 변환
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)


# ndarray 반환값 DataFrame 변환
iris_df_scaled = pd.DataFrame(iris_scaled, columns = iris.feature_names)
print('Feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nFeature 들의 분산 값')
print(iris_df_scaled.var())


print('\n결과적으로 모든 Feature의 평균값이 0에 아주 가까워진 것을 확인할 수 있다.')
print('또한 모든 Feature의 분산값이 1에 가까워진 것을 확인할 수 있다.')

Feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

Feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

결과적으로 모든 Feature의 평균값이 0에 아주 가까워진 것을 확인할 수 있다.
또한 모든 Feature의 분산값이 1에 가까워진 것을 확인할 수 있다.


# MinMaxScaler

#### 데이터 값을 0과 1 사이의 범위 값으로 변환.
#### 음수 값 존재할 경우 -1과 1 사이의 범위 값으로 변환.
#### 데이터 분포가 가우시안 분포가 아닐 경우 적용할 수 있는 모델.

In [24]:
from sklearn.preprocessing import MinMaxScaler


# MinMaxScaler 객체 생성
scaler = MinMaxScaler()


# Data Set 변환.
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)


# ndarray 반환값 DataFrame 변환.
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)
print('Feature 들의 최솟값')
print(iris_df_scaled.min())
print('\nFeature 들의 최대값')
print(iris_df_scaled.max())

Feature 들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

Feature 들의 최대값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


# 
# 
# 

# 학습 / 테스트 데이터 스케일링 변환 시 유의점

#### StandardScaler, MinMaxscaler 사용 시
#### fit(), transform(), fit_transform() 메서드 사용.
#### Training Data에 스케일링 적용했을 경우 Test Data 또한 스케일링 적용 필수.

In [28]:
# 학습 데이터는 0~10, 테스트 데이터는 0~5 값을 가지는 데이터 세트 생성
train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)


# MinMaxScaler 객체 생성
scaler = MinMaxScaler()


# Train Data Set 학습
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터 : ', np.round(train_array.reshape(-1), 2))
print('변환 train_array 데이터 : ', np.round(train_scaled.reshape(-1), 2))


# Test Data Set 학습
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)
print('원본 test_array 데이터 : ', np.round(test_array.reshape(-1), 2))
print('변환 test_array 데이터 : ', np.round(test_scaled.reshape(-1), 2))

원본 train_array 데이터 :  [ 0  1  2  3  4  5  6  7  8  9 10]
변환 train_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test_array 데이터 :  [0 1 2 3 4 5]
변환 test_array 데이터 :  [0.  0.2 0.4 0.6 0.8 1. ]


In [29]:
# Train Data는 각 숫자와 스케일링 데이터가 매치되는 반면
# Test Data는 숫자와 스케일링이 일치하지 않는다.
# 이는 fit() 이 두 번 적용되었기 때문.
# 학습 데이터를 기준으로 수행하기 때문에 fit()은 반드시 한 번 적용되어야 한다.


# Train Data Set 학습
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터 : ', np.round(train_array.reshape(-1), 2))
print('변환 train_array 데이터 : ', np.round(train_scaled.reshape(-1), 2))


# fit() 호출 없이 바로 transform()만으로 변환.
test_scaled = scaler.transform(test_array)
print('원본 test_array 데이터 : ', np.round(test_array.reshape(-1), 2))
print('변환 test_array 데이터 : ', np.round(test_scaled.reshape(-1), 2))

원본 train_array 데이터 :  [ 0  1  2  3  4  5  6  7  8  9 10]
변환 train_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test_array 데이터 :  [0 1 2 3 4 5]
변환 test_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5]
